### ISSUE TITLE
How to draw the figures?

### ISSUE THREAD

**Issue by kroniidvul** [hysts/pytorch_mpiigaze#10]
How can I recreate the figures for LeNet and Resnet as present in the 'figures' folder? I thought the argument tensorboard_images had something to do with drawing those figures, but I guess not. 
These are the parameters that I'm passing:
--arch lenet --dataset data --test_id 0 --outdir results/lenet/00 --batch_size 32 --base_lr 0.01 --momentum 0.9 --nesterov True --weight_decay 1e-4 --epochs 2 --lr_decay 0.1 --tensorboard --tensorboard_images --tensorboard_parameters
Everything else seems to work fine. I can visualize the histograms and loss-graphs in tensorboard. But the figures are not drawn.

**Comment by hysts** [comment]
I drew the figure using the evaluation results with jupyter notebook.
