### ISSUE TITLE
how to get my own camera params?

### ISSUE THREAD

**Issue by huxian0402** [hysts/pytorch_mpiigaze#11]
Good work, but how to get my own camera params to calibrate my camera in practice? @hysts

**Comment by hysts** [comment]
Hi, @huxian0402 
You can calibrate your camera using a checkerboard pattern and OpenCV functions as described in these articles.
https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html
https://www.learnopencv.com/camera-calibration-using-opencv/

**Comment by huxian0402** [comment]
Thanks a lot. @hysts 
And i have trained with resnet_preact_train_using_all_data.yaml for 40 epochs on mpiigaze. Then I evaluate checkpoint_0040.pth with resnet_preact_eval.yaml, but  the result is that  the mean angle error (deg) is less than 2.00 for each person id. It's good. But why the Mean Test Angle Error [degree] for your Results is 5.73?

**Comment by hysts** [comment]
@huxian0402 
Ah, `resnet_preact_train_using_all_data.yaml` is prepared for actual gaze estimation with webcam, not for training/evaluation experiments.
Using that YAML file, the model is trained with data from all 15 people. Since you are using data of all people, the score is for the training data itself. That's the reason why the test score seems so low.
In case of MPIIGaze/MPIIFaceGaze, in order to see the generalization performance to new unknown people, the model is evaluated by leave-one-person-out, which means the model should be trained on data from 14 people and tested on those of the remaining one person.

**Comment by huxian0402** [comment]
@hysts ,
Yes, I made a wrong test and now I understand. You really help me a lot. Thanks again.

**Comment by hysts** [comment]
Glad to hear that. :)

**Comment by Kelly-ZH** [comment]
> Hi, @huxian0402
> You can calibrate your camera using a checkerboard pattern and OpenCV functions as described in these articles.
> https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html
> https://www.learnopencv.com/camera-calibration-using-opencv/



> Hi, @huxian0402
> You can calibrate your camera using a checkerboard pattern and OpenCV functions as described in these articles.
> https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html
> https://www.learnopencv.com/camera-calibration-using-opencv/

Hi hysts,
I have a question which I hope you can answer. If I have already obtained my own camera parameters, do I modify them directly in [sample_params.yaml](https://github.com/hysts/pytorch_mpiigaze/blob/a8cb2e344068bf75c7fdbbd732db88fa09ddb618/data/calib/sample_params.yaml)?
Thanj you very much.

**Comment by hysts** [comment]
Hi, @Kelly-ZH 

That works, but basically the file is not supposed to be changed directly. You can specify your camera parameter file [here](https://github.com/hysts/pytorch_mpiigaze/blob/master/configs/demo_mpiigaze_resnet.yaml#L7).

**Comment by Kelly-ZH** [comment]
> Hi, @Kelly-ZH
> 
> That works, but basically the file is not supposed to be changed directly. You can specify your camera parameter file [here](https://github.com/hysts/pytorch_mpiigaze/blob/master/configs/demo_mpiigaze_resnet.yaml#L7).

Thank you for your soon reply. And I have two other question, that is, 

1. I have trained the resnet and lenet besed on mpiigaze dataset, but my evaluate datas are quite different from [yours](https://github.com/hysts/pytorch_mpiigaze/blob/master/figures/mpiigaze/lenet.png) . My resnet model works better than lenet model.  I'm a little confused.
2. How to draw the figure like [this](https://github.com/hysts/pytorch_mpiigaze/blob/master/figures/mpiigaze/lenet.png)

**Comment by hysts** [comment]
@Kelly-ZH 

1. Not sure what you mean. It's not strange ResNet outperforms LeNet. Could you be more specific?
2. You can use matplotlib to draw such figures:


```python
exp_rootdir = pathlib.Path('experiments/mpiigaze/lenet/exp00')
exp_dirs = sorted(exp_rootdir.glob('*'))
angle_errors = []
for exp_dir in exp_dirs:
    with open(exp_dir / 'eval/error.txt') as f:
        angle_errors.append(float(f.read()))
angle_errors = np.array(angle_errors)

plt.bar(np.arange(len(angle_errors)),
        angle_errors,
        color=plt.rcParams['axes.prop_cycle'].by_key()['color'])
plt.hlines(angle_errors.mean(), -0.5, 14.5, ls='--', color='blue')
plt.grid(alpha=0.5)
plt.xticks(np.arange(15), np.arange(15))
plt.xlabel('Person ID')
plt.ylabel('Angle Error [deg]')
plt.title('LeNet\n' f'Mean Angle Error: {angle_errors.mean():.2f} [deg]')
plt.show()
```

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> 1. Not sure what you mean. It's not strange ResNet outperforms LeNet. Could you be more specific?
> 2. You can use matplotlib to draw such figures:
> 
> ```python
> exp_rootdir = pathlib.Path('experiments/mpiigaze/lenet/exp00')
> exp_dirs = sorted(exp_rootdir.glob('*'))
> angle_errors = []
> for exp_dir in exp_dirs:
>     with open(exp_dir / 'eval/error.txt') as f:
>         angle_errors.append(float(f.read()))
> angle_errors = np.array(angle_errors)
> 
> plt.bar(np.arange(len(angle_errors)),
>         angle_errors,
>         color=plt.rcParams['axes.prop_cycle'].by_key()['color'])
> plt.hlines(angle_errors.mean(), -0.5, 14.5, ls='--', color='blue')
> plt.grid(alpha=0.5)
> plt.xticks(np.arange(15), np.arange(15))
> plt.xlabel('Person ID')
> plt.ylabel('Angle Error [deg]')
> plt.title('LeNet\n' f'Mean Angle Error: {angle_errors.mean():.2f} [deg]')
> plt.show()
> ```
About 1:

- first I run train.py with I modified test_id(0-14) in [lenet_train.yaml](https://github.com/hysts/pytorch_mpiigaze/blob/a8cb2e344068bf75c7fdbbd732db88fa09ddb618/configs/mpiigaze/lenet_train.yaml)/[resnet_preact_train.yaml](https://github.com/hysts/pytorch_mpiigaze/blob/a8cb2e344068bf75c7fdbbd732db88fa09ddb618/configs/mpiigaze/resnet_preact_train.yaml)  to get training models respectively.
- then I run evaluate.py to evaluate the model respectively. the evaluate data of resnet are generally better than that of lenet.

**Comment by hysts** [comment]
@Kelly-ZH 

Hmm... I'm confused. You said your evaluation result was quite different from mine, but your result seems to be just in line with mine.
As you may know, ResNet has a lot more capacity than LeNet, sot it's natural for ResNet to outperform LeNet. In fact, the results are exactly what we expect.

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> Hmm... I'm confused. You said your evaluation result was quite different from mine, but your result seems to be just in line with mine.
> As you may know, ResNet has a lot more capacity than LeNet, sot it's natural for ResNet to outperform LeNet. In fact, the results are exactly what we expect.

Thank you for your reply. I have found the mistakes, that is the model didn't agree with the evaluate data.  I really appreciate your kindness
