### ISSUE TITLE
3D face model for 106 points

### ISSUE THREAD

**Issue by huxian0402** [hysts/pytorch_mpiigaze#12]
There's a 3D face model for Multi-PIE 68 points mark-up in your code. But how to get a 3D face model for 106 points? I have a landmark model for 106 points. Thank you. @hysts

**Comment by hysts** [comment]
Hi, @huxian0402

I'm not sure if there is an easy way to create a 3D face model. In case of Multi-PIE 68 points, there is a dataset of 3D points like [this](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/main.htm), so you can use one of them or some average of them.
Maybe you should read the paper in the link above and see how the dataset was created. But I'm not sure if it's applicable to your case.

Also, if you have a sensor like Kinect, you can capture images with depth maps, so by capturing your face with it and applying your face alignment method to the captured image, you can get the depth of each points. If you want to create an average 3D model of multiple people, you will need to find someone who can help you capture their faces.

Hope it helps.

**Comment by huxian0402** [comment]
Thanks for your reply and it helps me a lot. It seems difficult to create an average 3D model of multiple people for 106 points for me. Alternatively,  I convert 106 points to 68 points according to the location mapping to continue using Multi-PIE 68 points 3D face models.
