### ISSUE TITLE
User distance from the sensor

### ISSUE THREAD

**Issue by dcazzato** [hysts/pytorch_mpiigaze#13]
Hello,
I am wondering if you already have a range of user distance w.r.t. the camera in the MPIIGaze dataset. I know that it could be extracted from the dataset with some script, but before doing it, I'd ask if you already have this data (I did not find this info the paper). 
Best,

**Comment by hysts** [comment]
Hi, @dcazzato

I don't have that data.

**Comment by dcazzato** [comment]
Thank you, I will solve using the old way :)
