### ISSUE TITLE
about normalized_camera_matrix

### ISSUE THREAD

**Issue by huxian0402** [hysts/pytorch_mpiigaze#14]
I have get a good result by following your project.  And I have a problem about,  how to cal the normalized_camera_matrix  as given in your code? @hysts  Thank you!

**Comment by hysts** [comment]
Hi, @huxian0402

The normalized camera matrix is not something you can get by computation but something you define.
See section 4.2 in [the paper](https://arxiv.org/abs/1711.09017).

BTW, glad to hear your project is going well. :)

**Comment by huxian0402** [comment]
Yes, the normalized matrix in your paper is the same as what is described in section 4.2 in the paper. Thanks, you help me a lot.
