### ISSUE TITLE
The yaml file of alexnet is missing during the demo

### ISSUE THREAD

**Issue by yb525533341** [hysts/pytorch_mpiigaze#17]
Hello, I used ALEXnet to train the data, but I am missing the DEMO configuration file, can you give a demo_mpiifacegaze_alexnet_simple_14.yaml

**Comment by hysts** [comment]
Hi, @yb525533341 

I don't have time to check it myself, so I'm not 100% sure, but I think the demo program will work if you change the camera parameter file and the config file as follows.

camera parameter file:

```
image_width: 448
image_height: 448
camera_matrix:
    rows: 3
    cols: 3
    data: [1600., 0., 224.,
           0., 1600., 224.,
           0., 0., 1.]
distortion_coefficients:
    rows: 1
    cols: 5
    data: [0., 0., 0., 0., 0.]
```

config file:

```
model:
  name: alexnet
transform:
  mpiifacegaze_face_size: 448
```

**Comment by yb525533341** [comment]
This can successfully run the demo, but it may be because of the camera parameters that the estimated gaze direction does not change significantly.
