### ISSUE TITLE
what is normalized_camera_params for?

### ISSUE THREAD

**Issue by Yijun88** [hysts/pytorch_mpiigaze#18]
Hi hysts,

Great work for the pytorch implementation! I was trying to understand the normalization process from the code and i found there's a normalized_camera_params.yaml that helped with the eye patch image normalization. Can I ask where do you get those information and why the camera matrix is different in the normalized_camera_params compared with the sample_params.yaml ?

## ====normalized_camera_params.yaml======
image_width: 60
image_height: 36
camera_matrix:
    rows: 3
    cols: 3
    data: [960., 0., 30,
           0., 960., 18.,
           0., 0., 1.]
distortion_coefficients:
    rows: 1
    cols: 5
    data: [0., 0., 0., 0., 0.]
## =================================

Best,
Yijun

**Comment by hysts** [comment]
Hi, @Yijun88 

You can find the explanation of the image normalization in section 4.2 of [this paper](https://arxiv.org/abs/1711.09017). I used parameters described in the paper for MPIIGaze, but I don't remember where I found parameters for MPIIFaceGaze. (I remember googling about it, so maybe in another paper?)

`sample_params.yaml` is a sample file for camera parameters of your real camera, and the parameters in `normalized_camera_params.yaml` are for a predefined virtual camera.
