### ISSUE TITLE
Where is model.pth?

### ISSUE THREAD

**Issue by KentaroOtomo** [hysts/pytorch_mpiigaze#19]
Hi, hysts.
In accordance with README.md, I trained ResNet-8 and lenet.
But when I run demo.py,  [Errno 2] No such file or directory: 'data/models/mpiigaze/resnet_preact/model.pth'
message appears.
How can I create model.pth?

**Comment by chrischang5** [comment]
Hi, @KentaroOtomo what was the fix to this? I am running into the same issue.
