### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by nhathoang0110** [hysts/pytorch_mpiigaze#21]
How can I demo on my photos or a video without using a webcam?

**Comment by hysts** [comment]
Hi, @nhathoang0110 

You can run demo on videos by setting `demo.use_camera` to `False` and specifying `demo.video_path` in a configuration file like [this one](https://github.com/hysts/pytorch_mpiigaze/blob/master/configs/demo_mpiigaze_resnet.yaml).
Currently, this repo doesn't support running demo on images, but you can use [this repo](https://github.com/hysts/pytorch_mpiigaze_demo) to run demo on both images and videos.
