### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by nhathoang0110** [hysts/pytorch_mpiigaze#22]
why my checkpoint( when I trained by your source code) cannot use for demo ?

**Comment by hysts** [comment]
Hi, @nhathoang0110 

Is this related to https://github.com/hysts/pytorch_mpiigaze/issues/21 ?
I don't know what your question is about. Would you give me a little more detail? Like error messages?

**Comment by nhathoang0110** [comment]
Hello. Sorry because my english is not good. I want to ask why I cannot use my checkpoint when I trained in your code ( 
It is in "./experiments/mpiigaze/lenet/exp00/all/checkpoint_0010.pth" ) ? I can only use pretrained model in this repo "https://github.com/hysts/pytorch_mpiigaze_demo"   to demo ?   Thanks you

**Comment by hysts** [comment]
@nhathoang0110 

Ah, I see. You need to use a config file like [this one](https://github.com/hysts/pytorch_mpiigaze_demo/blob/master/configs/demo_mpiigaze.yaml) to run demo with your model.
