### ISSUE TITLE
"EOFError: Ran out of input" when running "python train.py --config configs/mpiigaze/lenet_train.yaml"

### ISSUE THREAD

**Issue by tslever** [hysts/pytorch_mpiigaze#23]
hysts,

Would you be willing to help me debug the following "EOFError: Ran out of input", which I encountered after installing required libraries, downloading and extracting "MPIIGaze.tar.gz" to "C:\Users\thoma\Documents\AI\mpiigaze\datasets", running preprocess_mpiigaze.py, and executing "python train.py --config configs/mpiigaze/lenet_train.yaml"?

Thank you,

Tom Lever

<img width="953" alt="EOFError" src="https://user-images.githubusercontent.com/46533664/91650659-37a40200-ea50-11ea-940d-6d4748d278f1.PNG">

**Comment by hysts** [comment]
Hi, @tslever 

I'm not sure, but [this question](https://discuss.pytorch.org/t/cant-pickle-local-object-dataloader-init-locals-lambda/31857) in PyTorch forum seems to be relevant to your problem.
Would you change [this part](https://github.com/hysts/pytorch_mpiigaze/blob/master/gaze_estimation/transforms.py#L21-L28) of the code as follows and see if it works?

```python
def _scale(x):
    return x.astype(np.float32) / 255


def _add_channel(x):
    return x[None, :, :]


def _create_mpiigaze_transform(config: yacs.config.CfgNode) -> Any:
    transform = torchvision.transforms.Compose([
        torchvision.transforms.Lambda(_scale),
        torch.from_numpy,
        torchvision.transforms.Lambda(_add_channel),
    ])
    return transform
```

**Comment by tslever** [comment]
Commenting and inserting the following code resulted in the following error.

<img width="478" alt="modification" src="https://user-images.githubusercontent.com/46533664/91664254-fea17700-eabb-11ea-840d-897965d8514c.PNG">

<img width="953" alt="error" src="https://user-images.githubusercontent.com/46533664/91664262-05c88500-eabc-11ea-9fd2-78022f27c84f.PNG">

**Comment by hysts** [comment]
@tslever 

I suppose the error has something to do with [this issue](https://github.com/pytorch/pytorch/issues/37703).
What is your PyTorch version? It seems to have been fixed in 1.5.1. I tried older versions and got the error in 1.5.0 but not in 1.5.1 or 1.6.0 on Ubuntu.

**Comment by tslever** [comment]
I'm running torch 1.6.0 and torchvision 0.7.0 on Windows 10. I think I'll switch to Ubuntu, unless you have other suggestions.

**Comment by hysts** [comment]
@tslever 

I see. So it's not a version problem. I think it would be easier to switch to Ubuntu too.
