### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by nhathoang0110** [hysts/pytorch_mpiigaze#24]
what is the different MPIIGaze and MPIIFacegaze ?
Which dataset is of paper Deep Appearance-Based Gaze Estimation ? thanks

**Comment by hysts** [comment]
Hi, @nhathoang0110 

> what is the different MPIIGaze and MPIIFacegaze ?

Images in the MPIIGaze dataset are eyes and images in the MPIIFaceGaze dataset are faces.
See websites for each dataset: [MPIIGaze](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild/), [MPIIFaceGaze](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/its-written-all-over-your-face-full-face-appearance-based-gaze-estimation/)

> Which dataset is of paper Deep Appearance-Based Gaze Estimation ?

If the paper you are referring to is "MPIIGaze: Real-World Dataset and Deep Appearance-Based Gaze Estimation", they use the MPIIGaze dataset.
