### ISSUE TITLE
assert vector.shape == (3, ) None type | face_parts.py

### ISSUE THREAD

**Issue by pavankumarbn** [hysts/pytorch_mpiigaze#27]
Hello All,

I have been facing `assert vector.shape == (3, )` `AttributeError: NoneType object has no attribute shape` error all of a sudden. It was working well. I have changed nothing but all of a sudden it is throwing this proble. Could you help me to fix this issue. 

Regards,
Pavan

**Comment by hysts** [comment]
Hi, @pavankumarbn 

That's odd. The method seems to be called only in these lines.
https://github.com/hysts/pytorch_mpiigaze/blob/master/demo.py#L188
https://github.com/hysts/pytorch_mpiigaze/blob/master/demo.py#L194
But, in both cases, the error should occur one line before. I think you should recheck to see if nothing has really changed.

**Comment by pavankumarbn** [comment]
Hi @hysts,

Thank you very much for your quick response.

As you rightly mentioned it is occurring one line before. I rechecked it the same as before and as you mentioned. I quite worried about what went wrong, since there are zero changes made. 

` pitch, yaw = np.rad2deg(face.vector_to_angle(face.gaze_vector))
  File "/home/digits/data2/miniconda3/envs/torch/lib/python3.7/site-packages/ptgaze/common/face_parts.py", line 46, in vector_to_angle
    assert vector.shape == (3, )
AttributeError: 'NoneType' object has no attribute 'shape'`

Regards,
Pavan

**Comment by hysts** [comment]
@pavankumarbn 

Sorry, I'm confused. I think your error means `face.gaze_vector` is `None` in [this line](https://github.com/hysts/pytorch_mpiigaze/blob/master/demo.py#L194), but `face.gaze_vector` is also used in [one line before](https://github.com/hysts/pytorch_mpiigaze/blob/master/demo.py#L193). And if it's `None`, the following error should occur in line 193, and the program should stop before reaching line 194.
```
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

You might want to use debugger to see what's going on.

**Comment by pavankumarbn** [comment]
Hi @hysts 

Many thanks for your response. I have made some changes to the file to achieve some requirements.  

Please find the complete program [here](https://drive.google.com/file/d/1W_eCjMtlKxfMtSUKgKoh9jGJuUPZG9GQ/view?usp=sharing). I am trying to print gaze data. It was working fine before. 

Sure, I will use it.  

Regards,
PAvan

**Comment by hysts** [comment]
@pavankumarbn 

I think the error is caused by using a code snippet for MPIIFaceGaze when using MPIIGaze mode. In case of MPIIGaze, gaze vector is computed for each eye, and stored in `face.reye.gaze_vector` and `face.leye.gaze_vector` respectively, while `face.gaze_vector` remains `None`.
Your code works with option `--mode face`. Maybe you've accidentally changed the default option from `face` to `eye`.

**Comment by pavankumarbn** [comment]
@hysts 
Greetings! Thank you very much for your information. I changed accordingly as you suggested. It works now. I am able to get the tracked data. Thank you a lot.
Regards,
Pavan

**Comment by pavankumarbn** [comment]
Hello @hysts 
Could you please guide me in smoothing data/filtering techniques that could be used?  I am using eye movement data to achieve HRI. I want to eliminate subtle/little eye movement data.
