### ISSUE TITLE
Issues in preprocess_mpiigaze.py --> ValueError: Unknown mat file type, version 0, 0 

### ISSUE THREAD

**Issue by err-or** [hysts/pytorch_mpiigaze#28]
Hi, I am trying to use your preprocessing code for the mpiigaze dataset but I am encountering this issue while running the preprocess_mpiigaze.py file. 
![image](https://user-images.githubusercontent.com/61436133/107023905-487e3f80-6775-11eb-8826-8091ac1abdd9.png)

Here, under 'MPIIGaze/' I kept the total mpiigaze data that we can get from [here](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild/).  

FYI, I am using a virtual environment and the scipy version is: 1.6.0

I would appreciate any kind of help to resolve this issue. Thanks!

**Comment by hysts** [comment]
Hi, @err-or

Hmm, I have no idea what's going on. I downloaded the dataset again and ran the code, and it works fine with scipy 1.6.0 on my Ubuntu environment.
It may be an error that occurs in the Windows environment, but as I don't have a Windows environment, I can't check it myself.

I think it's unlikely, but maybe the mat file could be corrupted.
Is the md5sum of `MPIIGaze/Data/Normalized/p00/day01.mat` the same as `7f06339fc5e4e3f0ba8ff76c6d886bfe`?
And is it not possible to open the file with `scipy.io.loadmat` even if the md5sum is the same?

**Comment by err-or** [comment]
Hi @hysts, 

Thank you for your prompt response. Yes I have checked the md5sum and they are the same as you mentioned and I can also load the .mat file with `scipy.io.loadmat`. 

The problem was solely on my end as I copied the script out of the repository and running it separately from a different location. My apologies for the inconvenience. Thank you for your help. I am closing the issue.
