### ISSUE TITLE
 Unable to open file (unable to open file: name = 'datasets\MPIIFaceGaze\p00.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by LiuZiMing000** [hysts/pytorch_mpiigaze#29]
Hello, I run python tools/preprocess_mpiifacegaze.py --dataset datasets/MPIIFaceGaze -o datasets/ will report, Unable to open file (unable to open file: name ='datasets\MPIIFaceGaze\p00.mat', errno = 2 , error message ='No such file or directory', flags = 0, o_flags = 0) wrong, what is going on, I hope you can answer, thank you.

**Comment by hysts** [comment]
Hi, @LiuZiMing000 

I think the path to the dataset you specified is wrong. It's `datasets/MPIIFaceGaze_normalized`, not ` datasets/MPIIFaceGaze`.
