### ISSUE TITLE
are raw, pitch and phi and theta are same 

### ISSUE THREAD

**Issue by utkarshvadar** [hysts/pytorch_mpiigaze#3]
are raw, pitch and phi, theta are same. and how can we convert the estimated gaze_vec(raw and pitch) to screen coordinates

**Comment by hysts** [comment]
Yes, yaw and pitch are same as phi and theta. You can compute 3D gaze direction vector from yaw and pitch. See https://stackoverflow.com/questions/1568568/how-to-convert-euler-angles-to-directional-vector.
