### ISSUE TITLE
results of run_all_mpiigaze_resnet_preact.sh

### ISSUE THREAD

**Issue by yuyaya-foifoi** [hysts/pytorch_mpiigaze#30]
Thank you for sharing your great work.

I have a question about the evaluation results of run_all_mpiigaze_resnet_preact.sh. 
That is, why is the angle error low something like in the range of 1 to 2?

[Based on a code](https://github.com/hysts/pytorch_mpiigaze/blob/a8cb2e344068bf75c7fdbbd732db88fa09ddb618/gaze_estimation/datasets/__init__.py#L39),  My understanding is that run_all_mpiigaze_resnet_preact.sh evaluates test_id's data with a model trained on data that excludes test_id's data. 

So this is not something similar to [your previous comment](https://github.com/hysts/pytorch_mpiigaze/issues/11#issuecomment-612016452), I guess.

Thank you

**Comment by hysts** [comment]
Hi, @yuyaya-foifoi 

Hmm... That's strange. Something must be wrong, but I have no idea what.

**Comment by yuyaya-foifoi** [comment]
Thanks for the reply.
Just to confirm, the result of MPIIFaceGaze on README was calculated by running run_all_mpiigaze_resnet_preact.sh as I did?

**Comment by hysts** [comment]
@yuyaya-foifoi 

If you ran the code without any modification, that's the case. I ran the code again just in case, and got the similar results in the README.
Are you sure you are looking at the test results, not the val?

**Comment by yuyaya-foifoi** [comment]
Thank you

Quick check,

- val error will be written in experiments/mpiifacegaze/resnet_simple_14/exp00/00/log.txt
- test error will be written in experiments/mpiifacegaze/resnet_simple_14/exp00/00/eval/checkpoint_0015/error.txt

right?

**Comment by hysts** [comment]
Yes.

**Comment by yuyaya-foifoi** [comment]
Then I'm checking right txt file.

I'll retry 
>Download the dataset and preprocess it

again and see what happens.

**Comment by yuyaya-foifoi** [comment]
Hmm, somehow I could get a result something similar to the result written in README.
Bit weird but my problem was solved so I'll close this issue.

![スクリーンショット 2021-03-12 14 05 55](https://user-images.githubusercontent.com/40622501/110937983-84a94f00-8376-11eb-9649-ed75e44265a0.png)
