### ISSUE TITLE
Some questions about mpiigaze dataset.

### ISSUE THREAD

**Issue by Kelly-ZH** [hysts/pytorch_mpiigaze#35]
Hello, hysts.
  I have two questions as below, and I am looking forward to your reply. Thank you very much.
1. Why  assert the length of images, poses, gazes are 3000 [here](https://github.com/hysts/pytorch_mpiigaze/blob/43601e851bc82cee4323ce6b5abf0ab4ff2c0b60/gaze_estimation/datasets/mpiigaze.py#L22) ？ Is it because random select 1500 left eye images and 1500 right eye images from the full dataset?
2. When I run  
> python train.py --config configs/mpiigaze/lenet_train.yaml

why does [step(len(train_loader))](https://github.com/hysts/pytorch_mpiigaze/blob/43601e851bc82cee4323ce6b5abf0ab4ff2c0b60/train.py#L72) is 1181?  How to calculate this number？

**Comment by hysts** [comment]
@Kelly-ZH 

1. Yes.
2. 3000 (number of images per person) * 14 (number of person used for training) * 0.9 (ratio of training data) / 32 (batch size). The ratio of validation data is specified [here](https://github.com/hysts/pytorch_mpiigaze/blob/43601e851bc82cee4323ce6b5abf0ab4ff2c0b60/configs/mpiigaze/lenet_train.yaml#L17) and the ratio of training data is `1 - val_ratio`.

**Comment by Kelly-ZH** [comment]
You really did me a big favor. I know it. Thank you very much.
