### ISSUE TITLE
Model choosing

### ISSUE THREAD

**Issue by Kelly-ZH** [hysts/pytorch_mpiigaze#36]
Hi, hysts
  I have a strange question, why do you choose model resnet_preact_8 for mpiigaze dataset and resnet_14 for mpiifacegaze? Besides, the cited paper used VGG16 for mpiigaze and got 5.4 mean angle error, used a CNN with spatial weights  then got 4.8 angle error.
  Thank you very much.

Yours,
Kelly

**Comment by hysts** [comment]
@Kelly-ZH 

One reason was that I thought ResNet would perform better, and another reason was that AlexNet was too large to run on the CPU.
As for the depth, I just stopped there because I wanted a fast model and increasing the depth further didn't improve performance much.

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> One reason was that I thought ResNet would perform better, and another reason was that AlexNet was too large to run on the CPU.
> As for the depth, I just stopped there because I wanted a fast model and increasing the depth further didn't improve performance much.

So have you  tried resnet_preact_10 or even more layers？ Thank you.

**Comment by hysts** [comment]
@Kelly-ZH 

Well, there's no such thing as ResNet10 (because the depth of ResNet is 6n + 2 or 9n + 2 (See the ResNet papers)), but anyway, if you mean whether I've tried larger models, the answer is yes.
