### ISSUE TITLE
Evaluation Ambiguity

### ISSUE THREAD

**Issue by ld909** [hysts/pytorch_mpiigaze#4]
Hi there, we run your code but found the evaluation method you implemented might be ambiguous.
As code shows, you used the last epoch to make evaluation for the one witch is left out during training. There seems no model selection process so if we change the number of epochs, this might lead to another cross-person evaluation results

**Comment by hysts** [comment]
Hi, that's right. It's better idea to hold out some data for validation other than test data.

**Comment by hysts** [comment]
I fixed this problem long ago, but it seems I forgot to close it...
