### ISSUE TITLE
Questions about resnet_14

### ISSUE THREAD

**Issue by Kelly-ZH** [hysts/pytorch_mpiigaze#41]
Hi, hysts.
  I studied the code further and encountered new problems, and described as bellow:

1.  Did you get resnet_14 like this? first delete the 4th laywers、avg_pool and fc of resnet_18，then add a fc laywer.
2.  what does this [line code](https://github.com/hysts/pytorch_mpiigaze/blob/3077444ef597ef2224816d4b6fd8ca54c0ea10c8/gaze_estimation/models/mpiifacegaze/resnet_simple.py#L48) mean？Why should x be multiplied by y?

Thank you very much. I am looking forward your reply.

Yours,
Kelly

**Comment by hysts** [comment]
@Kelly-ZH 

1. Yes. And now I realized that [this comment](https://github.com/hysts/pytorch_mpiigaze/issues/36#issuecomment-808185943) about the size of ResNet was wrong. Sorry about that. I fixed it.
2. The `y` is the line is W in section 4.1 of [MPIIFaceGaze paper](https://arxiv.org/abs/1611.08860).

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> 1. Yes. And now I realized that [this comment](https://github.com/hysts/pytorch_mpiigaze/issues/36#issuecomment-808185943) about the size of ResNet was wrong. Sorry about that. I fixed it.
> 2. The `y` in the line is W in section 4.1 of [MPIIFaceGaze paper](https://arxiv.org/abs/1611.08860).

Thank you for your reply. About quetion 2, [the paper](https://arxiv.org/abs/1611.08860) propose to use additional three convolutional layers to learn spatial weights,  and you only use one 1*1 convolutional layer, is it?

**Comment by hysts** [comment]
@Kelly-ZH 

For ResNet, yes.

**Comment by Kelly-ZH** [comment]
Hi, hysts.
 I drew the model of resnet_14 and resnet_preact_8, you can refer to the attachments for details. Could you please help me to see what's wrong with my work, thank you very much.

Yours,
Kelly

发件人: hysts
发送时间: 2021年4月8日 9:55
收件人: hysts/pytorch_mpiigaze
抄送: Kelly-ZH; Mention
主题: Re: [hysts/pytorch_mpiigaze] Questions about resnet_14 (#41)

@Kelly-ZH
For ResNet, yes.

**Comment by hysts** [comment]
@Kelly-ZH 

I'm confused. Obviously, nothing is attached to your reply...
Did you forget to drag and drop your images or something? You can check if the image can be displayed correctly by clicking on the preview tab above before hitting the comment button.

**Comment by Kelly-ZH** [comment]
I am sorry, I didn’t upload the attachment successfully. I upload them as pictures again.


发件人: hysts
发送时间: 2021年4月9日 1:53
收件人: hysts/pytorch_mpiigaze
抄送: Kelly-ZH; Mention
主题: Re: [hysts/pytorch_mpiigaze] Questions about resnet_14 (#41)

@Kelly-ZH
I'm confused. Obviously, nothing is attached to your reply...
Did you forget to drag and drop your images or something? You can check if the image can be displayed correctly by clicking on the preview tab above before hitting the comment button.

**Comment by hysts** [comment]
@Kelly-ZH 

Are you replying to an email from GitHub? I'm not sure what's going on, but anyway, I can't see any images in this issue comment.

**Comment by Kelly-ZH** [comment]
I try it again. Can you see it now?
![resnet_14](https://user-images.githubusercontent.com/56919535/114137474-dc6bb380-993e-11eb-8fdd-ae8f365f384c.png)
![resnet_preact_8](https://user-images.githubusercontent.com/56919535/114137478-dd044a00-993e-11eb-98d5-3e421e800aa0.png)

**Comment by hysts** [comment]
@Kelly-ZH 

Yes, now I can see them. And they look fine.

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> Yes, now I can see them. And they look fine.

Thank you. For some personal reasons, I will delete the picture.  Hope you can understand.

**Comment by Kelly-ZH** [comment]
Hi , I have two other questions.  Can you answer it for me? Thank you.

1. Which datase is the pre-training model(resnet18) trained on? I can't find the relevant code.
2. what does this [line code](https://github.com/hysts/pytorch_mpiigaze/blob/3077444ef597ef2224816d4b6fd8ca54c0ea10c8/configs/mpiifacegaze/resnet_simple_14_train.yaml#L14) mean?

Thank you.

**Comment by Kelly-ZH** [comment]
> @Kelly-ZH
> 
> For ResNet, yes.
Hi, hysts
the paper propose to use additional three convolutional layers to learn spatial weights, and why did you only use one 1*1 convolutional layer? Could you answer it for me? 

Thank you very much.
