### ISSUE TITLE
Why are you only using the evaluation set (3000) images for both training and testing? 

### ISSUE THREAD

**Issue by err-or** [hysts/pytorch_mpiigaze#42]
Hi @hysts! Thank you for your work here. I am a bit confused about the MPIIGaze dataset that you are using for gaze estimation during training and testing. It seems like you are only using the evaluation set for both training and testing which contains 1500 left eye and 1500 right eye images, while the total dataset provides more images (normalized) specific to each participant.

Is there any particular reason as to why you are using only the evaluation set during training?

**Comment by hysts** [comment]
Hi, @err-or 

That's because that's the standard way to use the MPIIGaze dataset. Take a look at section 5 of [MPIIGaze paper](https://arxiv.org/abs/1711.09017).
