### ISSUE TITLE
Questions about resnet-simple-14

### ISSUE THREAD

**Issue by Kelly-ZH** [hysts/pytorch_mpiigaze#46]
Hi,hysts
  Firstly, thank you for your wonderful project, I can learn a lot from it. And when I was learning, I have several questions as follow,  can you answer them for me?

1. Why resnet-simple-14 has only one 1*1  convolution layer to learn spatial weight, and for the spatial weight CNN in [the paper](https://arxiv.org/abs/1611.08860), it has three 1*1  convolution layers?
2. I have trained resnet34 and resnet10 for the mpiifacegaze datasets, but they do worse than  resnet14? What do you think of this result? Can you explain it to me?

Thank you for your reading, and I am really looking forward to your reply.

**Comment by hysts** [comment]
Hi, @Kelly-ZH 

1. That's because the performance didn't improve even with three convolutional layers.
2. I'm not sure, but in general, a model with too many parameters could overfit.

**Comment by Kelly-ZH** [comment]
> Hi, @Kelly-ZH
> 
> 1. That's because the performance didn't improve even with three convolutional layers.
> 2. I'm not sure, but in general, a model with too many parameters could overfit.

Thank you very much.
