### ISSUE TITLE
Architecture of the resnet-preact used in MPIIGaze dataset

### ISSUE THREAD

**Issue by dreamer-1996** [hysts/pytorch_mpiigaze#51]
Hello :)
I am trying to understand the architecture of the resnet preact model used for the MPIIGaze dataset. More specifically, I am trying to visualize the architecture.
I am using a web service known as [NN-SVG](http://alexlenail.me/NN-SVG/LeNet.html) to auto-generate a diagram for the NN architecture. For that, I need to fill in some parameters on that web page.
Can you help me in finding those parameters from your code?
Thanks in advance.

**Comment by hysts** [comment]
Hi, @dreamer-1996 

The website doesn't seem to support visualizing ResNet-like architecture.
Anyway, you can get the information about the shape of the weights of the model by just running `print(model)` or something.

**Comment by hysts** [comment]
@dreamer-1996 

I added [this file](https://github.com/hysts/pytorch_mpiigaze/blob/master/convert_to_onnx.py) to this repo.
You can get the onnx model by running the following:

```bash
python convert_to_onnx.py --config configs/mpiigaze/resnet_preact_eval.yaml -o out.onnx
```

You can then use [Netron](https://netron.app/) to visualize the model.
The visualization results are shown below.

![](https://user-images.githubusercontent.com/25161192/131391673-148c8f87-8fc9-4352-a57e-0ae96c6e57fc.png)

**Comment by dreamer-1996** [comment]
Thank you very much @hysts 
Can you explain me the output shape? (what's happening in the last concat?)

**Comment by hysts** [comment]
@dreamer-1996 

It just concatenates the head pose vector and applies a linear transformation. Take a look at [these lines](https://github.com/hysts/pytorch_mpiigaze/blob/master/gaze_estimation/models/mpiigaze/resnet_preact.py#L129-L130).

**Comment by dreamer-1996** [comment]
Thank you for the reply :) I got my answer.
