### ISSUE TITLE
Test error for myself.

### ISSUE THREAD

**Issue by gdww97** [hysts/pytorch_mpiigaze#52]
Hi,
Thank you so much for your work. It is beneficial for us to learn the gaze estimation area.
Did you test the error use your own dataset? I mean use yourself.
I test myself but the gaze angle or vector error is so big. I do not know the reason why the error is so big. I guess that the face model 68 3D points is the major reason, and I use the standard face model. If I use my own face model, the gaze accuracy will be higher?
Thanks!

**Comment by hysts** [comment]
Hi, @gdww97 

Yes, I tested the model with my own face using webcam.
The 3D face model could be the reason, but before that, are you sure you calibrated your camera correctly? If the error is very large, you might want to check that first.

**Comment by gdww97** [comment]
Yes, I calib my camera first. Next, I will test the results again using my own 3D face model. Thanks!

**Comment by gdww97** [comment]
Another problem, the origin of face is set the midpoint of right eye in the paper. However, in code face_model.py, the origin is at the tip of the nose. If the results will be different between the two coordinate system? And if I use my own 3D face model, which coordinate should I use?
Thanks!

**Comment by hysts** [comment]
@gdww97 

The center of the eye is computed [here](https://github.com/hysts/pytorch_mpiigaze/blob/34d7d2fd9102688bc7a523a6f1d9542f8b934aa8/gaze_estimation/gaze_estimator/common/face_model.py#L138-L150) and the image normalization is done [here](https://github.com/hysts/pytorch_mpiigaze/blob/34d7d2fd9102688bc7a523a6f1d9542f8b934aa8/gaze_estimation/gaze_estimator/head_pose_estimation/head_pose_normalizer.py#L19-L23) using it, so I think you don't have to worry about it.

**Comment by gdww97** [comment]
OK, many thanks!
