### ISSUE TITLE
xgaze train code please

### ISSUE THREAD

**Issue by w359405949** [hysts/pytorch_mpiigaze#54]
xgaze train code please.

**Comment by hysts** [comment]
OK. I'll publish the code after refactoring it.

**Comment by w359405949** [comment]
thx @hysts

**Comment by hysts** [comment]
@w359405949 

The training code for ETH-XGaze is now available [here](https://github.com/hysts/pl_gaze_estimation). Enjoy!

**Comment by w359405949** [comment]
thx @hysts
