### ISSUE TITLE
denormalize_gaze_vector

### ISSUE THREAD

**Issue by fengyanWang** [hysts/pytorch_mpiigaze#57]
Hello, thank you very much for your open source work. Here's a question for you. After I get the output of the model, can I get the real-world line of sight angle value without 3D mapping?

**Comment by hysts** [comment]
Hi, @fengyanWang 
I'm not sure what you mean by "without 3D mapping", but `denormalize_gaze_vector` is definitely needed. Section 4.2 of [this paper](https://arxiv.org/abs/1711.09017) would help you understand what it does and why it's necessary.
