### ISSUE TITLE
does the output result cotain 3d position of eye?

### ISSUE THREAD

**Issue by eugeneYz** [hysts/pytorch_mpiigaze#58]
Hi! Can l get the 3d positon of eye or the center of the face?

**Comment by hysts** [comment]
Hi, @eugeneYz 

You can get those values [here](https://github.com/hysts/pytorch_mpiigaze/blob/ea0a10ea2d0b4cb2c5dd035a4e3ad4b0cf414829/gaze_estimation/gaze_estimator/common/face_model.py#L138-L150). If you want to compute them with different definition, you can use the fitted result of the 3D face model stored [here](https://github.com/hysts/pytorch_mpiigaze/blob/ea0a10ea2d0b4cb2c5dd035a4e3ad4b0cf414829/gaze_estimation/gaze_estimator/common/face_model.py#L133-L136). Note that the fitting is done by rigid transformation, so, even if the eyes are closed in the input image, the eyes of the fitted 3D landmarks are not closed.

**Comment by XiaoLaoDi** [comment]
Hi, @hysts the [solvePnP in opencv](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga549c2075fac14829ff4a58bc931c033d), returns rvec and tvec as coded in [here](https://github.com/hysts/pytorch_mpiigaze/blob/ea0a10ea2d0b4cb2c5dd035a4e3ad4b0cf414829/gaze_estimation/gaze_estimator/common/face_model.py#L119), the rvec and tvec transforms the world coordinate system to camera coordinate system, so is the [calculation of model3d in here](https://github.com/hysts/pytorch_mpiigaze/blob/ea0a10ea2d0b4cb2c5dd035a4e3ad4b0cf414829/gaze_estimation/gaze_estimator/common/face_model.py#L136) should be  `model3d = (rot @ LANDMARKS_FACE.T).T + tvec`, so would you mind to clarify that, its really a little bit comfusing.
