### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by liushifu12138** [hysts/pytorch_mpiigaze#61]
When I run the demo on WIN, Frame doesn't show Gaze Estimation?

![9ee16bc1c41166e00a30beadc6c2a8d](https://user-images.githubusercontent.com/71754694/180745431-54f0c98d-c9da-47b7-8ecd-c49fcde915af.png)

**Comment by hysts** [comment]
I think https://github.com/hysts/pytorch_mpiigaze_demo/issues/31 is basically the same question, so I'll answer it there and close this one.
