### ISSUE TITLE
Assertion Error MPIIGaze.h5

### ISSUE THREAD

**Issue by gaga1313** [hysts/pytorch_mpiigaze#62]
The script used for downloading the MPIIGaze data does not download any **MPIIGaze.h5** file, which is required for executing the train.py . The train.py program throws an error since the **create_dataset** function could not locate the path present in _config.dataset.dataset_dir_ that is **datasets/MPIIGaze.h5**

**Error:**
![image](https://user-images.githubusercontent.com/63440697/181471108-ca12b10d-2d38-458a-92d0-0c8466fab092.png)

Thankyou

**Comment by hysts** [comment]
Hi, @gaga1313 

Have you run both of these commands?
```bash
bash scripts/download_mpiigaze_dataset.sh
python tools/preprocess_mpiigaze.py --dataset datasets/MPIIGaze -o datasets/
```
The original MPIIGaze dataset is in tar.gz format and can be downloaded with the first command. The second command creates the h5 dataset from it.

**Comment by gaga1313** [comment]
Oh, I missed the second one. Thanks
