### ISSUE TITLE
how to make dataset

### ISSUE THREAD

**Issue by ChiwoongLEE** [hysts/pytorch_mpiigaze#63]
Hello, thank you for sharing your valuable dataset.

I chose mpiigaze dataset as my first deep learning model as an undergraduate.

As a result of analyzing the mpiigaze data set, it was confirmed that various data and png files consisting of mat files were included.

I want to make the same as mpiigaze dataset with eye tracker device called pupil core.
Can you give me some simple advice on how to make a dataset?

Also , as input data, can I build a dataset with only 3d gaze point and head_pose extracted with eye tracker equipment?

**Comment by hysts** [comment]
Hi, @ChiwoongLEE 
Sorry for the confusion. I'm not the author of the MPIIGaze paper and this is an unofficial implementation. About your questions, I think you should contact the authors. You can find contact information in their [project page](https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/research/gaze-based-human-computer-interaction/appearance-based-gaze-estimation-in-the-wild/).

**Comment by ChiwoongLEE** [comment]
oh sorry thank you very much 

Is the only dataset you used to train mpiigaze in Data/nomalized?

I am curious about the role of the annotation subset and evaluation subset folders in the MPIIGAZE dataset. I don't understand what is described on the official site.

**Comment by hysts** [comment]
@ChiwoongLEE 

> Is the only dataset you used to train mpiigaze in Data/nomalized?

Yes.

> I am curious about the role of the annotation subset and evaluation subset folders in the MPIIGAZE dataset. I don't understand what is described on the official site.

It seems they are described in section 3.3 of [their paper](https://arxiv.org/abs/1711.09017). For further detail, I recommend that you ask the authors directly.

**Comment by ChiwoongLEE** [comment]
thank you for your advise
