### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by ChiwoongLEE** [hysts/pytorch_mpiigaze#64]
Hi I have confirmed that you are training the model based on the .mat file of the nominalized folder through your open source.

In my case, I can get 3d gaze and head pose values from the pupil core (eye tracker).

Is it possible to learn the model by making these values like a .mat file of normalized and building my own dataset?
I wonder if I need an img file in this case.

**Comment by hysts** [comment]
@ChiwoongLEE 
> Is it possible to learn the model by making these values like a .mat file of normalized and building my own dataset?
> I wonder if I need an img file in this case.

I'm not sure what you mean by the second sentence, but if you have eye images, 3D gaze vectors and head pose vectors, I think you can normalize the images and create your own dataset. I'm not familiar with the dataset creation part, though, as I used preprocessed data included in the MPIIGaze dataset, and didn't create the dataset from the raw data myself.
