### ISSUE TITLE
How to convert gaze and plot on image?

### ISSUE THREAD

**Issue by WuZhuoran** [hysts/pytorch_mpiigaze#8]
Given an image of eye, we supposed to get a predicted result gaze [theta, phi],
We need to first convert to [x, y, z] vector, then plot on the image.

How to convert and how to calculate the position [x', y'] on the screen?
(Given the center of eye position is x1, y1)

Thank you.

**Comment by trakaros** [comment]
* Please check here:https://github.com/trakaros/MPIIGaze/issues/2
